name:                 spreadsheet-lang
version:              0.1.0.0
visibility:           public
id:                   spreadsheet-lang-0.1.0.0-inplace
key:                  spreadsheet-lang-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:
    SpreadsheetLang SpreadsheetLang.AST SpreadsheetLang.Parser

import-dirs:
    /Users/malgorzatadzaman/Desktop/University/Haskell-Course-2026/project/dist-newstyle/build/aarch64-osx/ghc-9.12.2/spreadsheet-lang-0.1.0.0/build

library-dirs:
    /Users/malgorzatadzaman/Desktop/University/Haskell-Course-2026/project/dist-newstyle/build/aarch64-osx/ghc-9.12.2/spreadsheet-lang-0.1.0.0/build

library-dirs-static:
    /Users/malgorzatadzaman/Desktop/University/Haskell-Course-2026/project/dist-newstyle/build/aarch64-osx/ghc-9.12.2/spreadsheet-lang-0.1.0.0/build

dynamic-library-dirs:
    /Users/malgorzatadzaman/Desktop/University/Haskell-Course-2026/project/dist-newstyle/build/aarch64-osx/ghc-9.12.2/spreadsheet-lang-0.1.0.0/build

data-dir:
    /Users/malgorzatadzaman/Desktop/University/Haskell-Course-2026/project/.

hs-libraries:         HSspreadsheet-lang-0.1.0.0-inplace
depends:
    base-4.21.0.0-958c containers-0.7-f896 mgprsc-9.7.0-e24310bb
    text-2.1.2-b3a1

haddock-interfaces:
    /Users/malgorzatadzaman/Desktop/University/Haskell-Course-2026/project/dist-newstyle/build/aarch64-osx/ghc-9.12.2/spreadsheet-lang-0.1.0.0/doc/html/spreadsheet-lang/spreadsheet-lang.haddock

haddock-html:
    /Users/malgorzatadzaman/Desktop/University/Haskell-Course-2026/project/dist-newstyle/build/aarch64-osx/ghc-9.12.2/spreadsheet-lang-0.1.0.0/doc/html/spreadsheet-lang
